version: '3'
name: 'IrisSystems'
services:
  railsapp:
    build: ./Shopping-App-IRIS
    command: bash -C '/usr/bin/deploy.sh'
    depends_on:
      railsmysql:
        condition: service_healthy
    ports:
      - "8080:3000"
    env_file: 
      - iris_app.env
    links:
      - railsmysql:db
    restart: on-failure:10

  railsmysql:
    image: mysql:5.7
    volumes:
      - ../data/ShoppingApp/backup/mysql:/var/lib/mysql
    env_file:
      - iris_mysql.env
    ports: 
      - "3306"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 30s
    restart: on-failure:10
    

